version: '3.9'

services:
  postgres:
    image: postgres
    restart: always
    container_name: postgres
    environment:
      POSTGRES_DB: builders
      POSTGRES_USER: builders
      POSTGRES_PASSWORD: builders
    volumes:
      - .docker/pgdata:/var/lib/postgresql/data
    ports:
      - 5432:5432
    networks:
      - postgres-network
  
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: "malikoski@gmail.com"
      PGADMIN_DEFAULT_PASSWORD: "builders"
    ports:
      - 16543:80
    depends_on:
      - postgres
    networks:
      - postgres-network

  flyway:
    image: flyway/flyway:7.11.2-alpine
    container_name: flyway
    command: -url=jdbc:postgresql://postgres:5432/builders -schemas=public -user=builders -password=builders -baselineOnMigrate=true -locations=filesystem:/flyway/sql migrate
    volumes:
      - ./db.migration:/flyway/sql
    depends_on:
      - postgres
    networks:
      - postgres-network

  redis:
    image: redis
    ports:
      - 6379:6379

  cliente-api:
   image: 'cliente-api:latest'
   build:
     dockerfile: Dockerfile
     context: .
   container_name: cliente-api-service
   ports:
     - 8080:8080
   depends_on:
     - postgres
     - redis
   environment:
     SPRING_REDIS_HOST: redis
     SPRING_REDIS_PORT: 6379
     DATABASE_URL: postgres
   networks:
     - postgres-network


networks:
  postgres-network:
    driver: bridge
