server:
  port: ${PORT}
spring:
  datasource:
    hikari:
      connectionTimeout: 20000
      maximumPoolSize: 5
    url: ${JDBC_DATABASE_URL}
    username: ${JDBC_DATABASE_USERNAME}
    password: ${JDBC_DATABASE_PASSWORD}
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  cache:
    type: redis
  redis:
    url: ${REDIS_URL}

  mustache:
    check-template-location: false

  logging:
    level:
      org.springframework.web: DEBUG

  ## Actuator config
management:
  endpoints:
    web:
      exposure:
        include: health,metrics,info,mappings
    health:
      show-details: always
    metrics:
      enabled: true



springdoc:
  version: '@springdoc.version@'
#  swagger-ui:
#    use-root-path: true
  #api-docs:
#    path: /api-docs