spring:
  datasource:
    hikari:
      connectionTimeout: 20000
      maximumPoolSize: 5
    url: ${JDBC_DATABASE_URL:jdbc:postgresql://localhost}:5432/builders}
    username: ${JDBC_DATABASE_USERNAME:builders}
    password: ${JDBC_DATABASE_PASSWORD:builders}
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  cache:
    type: redis
  redis:
    host: ${SPRING_REDIS_HOST:localhost}
    port: ${SPRING_REDIS_PORT:6379}

  mustache:
    check-template-location: false

  logging:
    level:
      org.springframework.web: DEBUG

  ## Actuator config
management:
  endpoints:
    web:
      exposure:
        include: health,metrics,info,mappings
    health:
      show-details: always
    metrics:
      enabled: true



springdoc:
  version: '@springdoc.version@'
#  swagger-ui:
#    use-root-path: true
  #api-docs:
#    path: /api-docs